import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google"; // Leave Inter import
import { AppProvider } from "@/providers/app-provider";
import { Theme } from "@/providers/theme";
import "@/styles/globals.css";
import { cx } from "@/utils/cx";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Starter kit — Untitled UI",
  description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
  themeColor: "#7f56d9",
  colorScheme: "light dark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cx(inter.variable, "bg-primary antialiased")}>
        <AppProvider>
          {/* Theme shu yerda bo‘lsa, modal ham shu konteynerga portal bo‘lishi kerak */}
          <Theme>
            <Toaster position="top-right" richColors closeButton />
            {/* ✅ MUHIM: portal container */}
            <div id="app-shell" className="min-h-dvh">
              {children}
            </div>
          </Theme>
        </AppProvider>
      </body>
    </html>
  );
}
